# Generated by Django 4.2 on 2025-01-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_booking_delete_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('jazzcash', 'JazzCash'), ('easypaisa', 'Easypaisa'), ('on_checkup', 'Cash on Checkup')], max_length=20),
        ),
    ]
