# Generated by Django 4.2 on 2025-01-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_booking_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
    ]
