# Generated by Django 4.2 on 2025-04-24 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_remove_booking_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendlyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_uri', models.URLField(help_text="Calendly's unique event URL or identifier", max_length=255, unique=True)),
                ('event_type', models.CharField(help_text="Type of webhook event (e.g. 'invitee.created', 'invitee.canceled')", max_length=100)),
                ('raw_payload', models.JSONField(help_text='Full JSON payload received from Calendly webhook')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this webhook was processed')),
                ('appointment', models.ForeignKey(blank=True, help_text='Link back to the internal Booking, if mapped', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendly_events', to='appointments.booking')),
            ],
            options={
                'verbose_name': 'Calendly Event',
                'verbose_name_plural': 'Calendly Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
