# Generated by Django 4.2 on 2024-12-20 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('cnic', models.CharField(max_length=15, unique=True)),
                ('cnic_front', models.ImageField(upload_to='consultants/cnic_front/')),
                ('cnic_back', models.ImageField(upload_to='consultants/cnic_back/')),
                ('office_address', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='consultants/thumbnails/')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('financial', 'Financial'), ('legal', 'Legal'), ('health', 'Health')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending Approval')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
