# Generated by Django 4.2 on 2024-12-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='cnic_back',
            field=models.ImageField(blank=True, upload_to='consultants/cnic_back/'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='cnic_front',
            field=models.ImageField(blank=True, upload_to='consultants/cnic_front/'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='consultants/thumbnails/'),
        ),
    ]
