# Generated by Django 4.2 on 2024-12-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0002_alter_consultant_cnic_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
