# Generated by Django 4.2 on 2024-12-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0003_consultant_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='about_info',
            field=models.TextField(default='No information available', max_length=1000),
        ),
    ]
