# Generated by Django 4.2 on 2025-01-14 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0004_consultant_about_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='email',
        ),
    ]
