# Generated by Django 4.2 on 2025-01-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0005_remove_consultant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
