# Generated by Django 4.2 on 2025-01-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0006_alter_consultant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='phone',
        ),
        migrations.AlterField(
            model_name='consultant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
