# Generated by Django 4.2 on 2025-01-22 09:43

import consultants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0007_remove_consultant_phone_alter_consultant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='cnic_back',
            field=models.ImageField(blank=True, upload_to=consultants.models.cnic_back_path),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='cnic_front',
            field=models.ImageField(blank=True, upload_to=consultants.models.cnic_front_path),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=consultants.models.thumbnail_path),
        ),
    ]
